/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        obsidian: '#08090A',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#45474c',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#545f73',
        primary: '#091426',
        'on-primary': '#ffffff',
        'primary-container': '#1e293b',
        'on-primary-container': '#8590a6',
        'inverse-primary': '#bcc7de',
        secondary: '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        tertiary: '#1e1200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#35260c',
        'on-tertiary-container': '#a38c6a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e3fb',
        'primary-fixed-dim': '#bcc7de',
        'on-primary-fixed': '#111c2d',
        'on-primary-fixed-variant': '#3c475a',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary-fixed': '#fadfb8',
        'tertiary-fixed-dim': '#ddc39d',
        'on-tertiary-fixed': '#271902',
        'on-tertiary-fixed-variant': '#564427',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        'slate-border': '#E2E8F0',
        'stage-d0-blue': '#3B82F6',
        'stage-d1-amber': '#F59E0B',
        'stage-d2-orange': '#F97316',
        'stage-d3-indigo': '#6366F1',
        'stage-d4-emerald': '#10B981',
      },
      fontFamily: {
        'hanken': ['Hanken Grotesk', 'sans-serif'],
        'source': ['Source Sans 3', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
